#ifndef RCC_H
#define RCC_H

#define RCC_CR_HSION        ((1<<0))
#define RCC_CR_HSIRDY       ((1<<1))
#define RCC_CR_HSITRIM_0    ((1<<3))
#define RCC_CR_HSITRIM_1    ((1<<4))
#define RCC_CR_HSITRIM_2    ((1<<5))
#define RCC_CR_HSITRIM_3    ((1<<6))
#define RCC_CR_HSITRIM_4    ((1<<7))
#define RCC_CR_HSEON        ((1<<16))
#define RCC_CR_HSERDY       ((1<<17))
#define RCC_CR_HSEBYP       ((1<<18))
#define RCC_CR_CSSON        ((1<<19))
#define RCC_CR_PLLON        ((1<<24))
#define RCC_CR_PLLI2SON     ((1<<26))
#define RCC_CR_PLLSAION     ((1<<28))

#define RCC_PLLCFGR_PLLM_0  ((1<<0))
#define RCC_PLLCFGR_PLLM_1  ((1<<1))
#define RCC_PLLCFGR_PLLM_2  ((1<<2))
#define RCC_PLLCFGR_PLLM_3  ((1<<3))
#define RCC_PLLCFGR_PLLM_4  ((1<<4))
#define RCC_PLLCFGR_PLLM_5  ((1<<5))
#define RCC_PLLCFGR_PLLN_0  ((1<<6))
#define RCC_PLLCFGR_PLLN_1  ((1<<7))
#define RCC_PLLCFGR_PLLN_2  ((1<<8))
#define RCC_PLLCFGR_PLLN_3  ((1<<9))
#define RCC_PLLCFGR_PLLN_4  ((1<<10))
#define RCC_PLLCFGR_PLLN_5  ((1<<11))
#define RCC_PLLCFGR_PLLN_6  ((1<<12))
#define RCC_PLLCFGR_PLLN_7  ((1<<13))
#define RCC_PLLCFGR_PLLN_8  ((1<<14))
#define RCC_PLLCFGR_PLLP_0  ((1<<16))
#define RCC_PLLCFGR_PLLP_1  ((1<<17))
#define RCC_PLLCFGR_PLLSRC  ((1<<22))
#define RCC_PLLCFGR_PLLQ_0  ((1<<24))
#define RCC_PLLCFGR_PLLQ_1  ((1<<25))
#define RCC_PLLCFGR_PLLQ_2  ((1<<26))
#define RCC_PLLCFGR_PLLQ_3  ((1<<27))
#define RCC_PLLCFGR_PLLR_0  ((1<<28))
#define RCC_PLLCFGR_PLLR_1  ((1<<29))
#define RCC_PLLCFGR_PLLR_2  ((1<<30))

#define RCC_CFGR_SW_0       ((1<<0))
#define RCC_CFGR_SW_1       ((1<<1))
#define RCC_CFGR_SWS_0      ((1<<2))
#define RCC_CFGR_SWS_1      ((1<<3))
#define RCC_CFGR_HPRE_0     ((1<<4)) 
#define RCC_CFGR_HPRE_1     ((1<<5))
#define RCC_CFGR_HPRE_2     ((1<<6))
#define RCC_CFGR_HPRE_3     ((1<<7))
#define RCC_CFGR_PPRE1_0    ((1<<10))
#define RCC_CFGR_PPRE1_1    ((1<<11))
#define RCC_CFGR_PPRE1_2    ((1<<12))
#define RCC_CFGR_PPRE2_0    ((1<<13))
#define RCC_CFGR_PPRE2_1    ((1<<14))
#define RCC_CFGR_PPRE2_2    ((1<<15))
#define RCC_CFGR_RTCPRE_0   ((1<<16))
#define RCC_CFGR_RTCPRE_1   ((1<<17))
#define RCC_CFGR_RTCPRE_2   ((1<<18))
#define RCC_CFGR_RTCPRE_3   ((1<<19))
#define RCC_CFGR_RTCPRE_4   ((1<<20))
#define RCC_CFGR_MCO1_0     ((1<<21))
#define RCC_CFGR_MCO1_1     ((1<<22))
#define RCC_CFGR_MCO1_PRE_0 ((1<<24))
#define RCC_CFGR_MCO1_PRE_1 ((1<<25))
#define RCC_CFGR_MCO1_PRE_2 ((1<<26))
#define RCC_CFGR_MCO2_PRE_0 ((1<<27))
#define RCC_CFGR_MCO2_PRE_1 ((1<<28))
#define RCC_CFGR_MCO2_PRE_2 ((1<<29))
#define RCC_CFGR_MCO2_0     ((1<<30))
#define RCC_CFGR_MCO2_1     ((1<<31))

#define RCC_APB1ENR_PWREN   ((1<<28))

void rcc_init(void);

#endif // RCC_H